### ISSUE TITLE
Should allow picking a destination or area and using forecast based on that

### ISSUE THREAD

**Issue by ckdake** [skalnik/whattowear.bike#1]

**Comment by skalnik** [comment]
Yeah I dig it. Sadly the service I'm using for weather specifically demands coordinates instead of a name. However we can use Google Maps geocoding service for that

**Comment by ckdake** [comment]
Ugh Google Maps has nastyish stuff in it's license. IIRC you can only use their geocoding if the end result is on a Google Map.

http://openweathermap.org/current  -> much nicer licensing and you can use city name
