### ISSUE TITLE
Remove geolocation + weather detection

### ISSUE THREAD

**Issue by skalnik** [skalnik/whattowear.bike#8]
Darksky is going away and this whole thing isn't the best since I usually am checking weather elsewhere and at different times.

**Comment by open-meteo** [comment]
Hi! Creator of open-meteo here.

I created a non-commercial no-api-key weather api. Maybe it could be of help, in case you want to update to another API without using your CC.

I do not have geolocation yet, but it sound feasible to add.

Best, Jeff

**Comment by skalnik** [comment]
Closed by https://github.com/skalnik/whattowear.bike/pull/11
